name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    environment: PROD

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
      - run: echo "This is my ENV Secrets ${{PROD.MONGO_URI}}"
      - run: echo "This is my ENV Secrets ${{PROD}}"
      # - run: |
      #     ${{PROD}}
      #     ${{PROD.MONGO_URI}}
      - run: npm run build --if-present
      - run: npm start
      # - run: |
      #     pm2 start --name dims npm -- start
      #     pm2 startup
      #     pm2 save
