name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

      MERCHANT_U_ID: ${{ secrets.MERCHANT_U_ID }}
      API_USER_ID: ${{ secrets.API_USER_ID }}
      API_KEY: ${{ secrets.API_KEY }}

      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_KEY: ${{ secrets.SMTP_KEY }}

      S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
      APPLICATION_KEY: ${{ secrets.APPLICATION_KEY }}
      APPLICATION_KEY_ID: ${{ secrets.APPLICATION_KEY_ID }}
      APPLICATION_KEY_NAME: ${{ secrets.APPLICATION_KEY_NAME }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
      - run: |
          pm2 delete all
      - run: npm run build --if-present
      - run: |
          pm2 start --name dims npm -- start
          pm2 startup
          pm2 save
